using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ZeusInspector.Generators;

[Generator(LanguageNames.CSharp)]
public class ExportStructGenerator : IIncrementalGenerator
{
    private const string ExportStructAttributeName = "ZeusInspector.Attributes.ExportStructAttribute";
    private const string InspectorRangeAttributeName = "ZeusInspector.Attributes.InspectorRangeAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var fieldInfo = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is FieldDeclarationSyntax,
                transform: (ctx, ct) => GetExportedStructInfo(ctx, ct))
            .Where(info => info.HasValue)
            .Select((info, _) => info!.Value);

        var collected = fieldInfo.Collect();

        context.RegisterSourceOutput(collected, GenerateCode);
    }

    private static ExportedStructFieldInfo? GetExportedStructInfo(
        GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var fieldDecl = (FieldDeclarationSyntax)ctx.Node;
        var model = ctx.SemanticModel;

        foreach (var variable in fieldDecl.Declaration.Variables)
        {
            var symbol = model.GetDeclaredSymbol(variable, ct) as IFieldSymbol;
            if (symbol == null) continue;

            var exportAttr = symbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == ExportStructAttributeName);
            if (exportAttr == null) continue;

            if (symbol.Type is not INamedTypeSymbol structType) continue;
            if (structType.TypeKind != TypeKind.Struct) continue;

            var structFields = structType.GetMembers()
                .OfType<IFieldSymbol>()
                .Where(f => !f.IsStatic)
                .ToList();

            if (structFields.Count == 0) continue;

            string rawName = variable.Identifier.Text;
            string groupName = ToPascalCase(TrimUnderscore(rawName));
            string prefix = ToSnakeCase(rawName);

            return new ExportedStructFieldInfo
            {
                ClassName = symbol.ContainingType.Name,
                ContainingNamespace = symbol.ContainingNamespace.IsGlobalNamespace
                    ? null
                    : symbol.ContainingNamespace.ToDisplayString(),
                FieldName = rawName,
                GroupName = groupName,
                Prefix = prefix,
                StructFields = structFields.Select(sf => new GeneratedStructField
                {
                    Name = sf.Name,
                    TypeName = GetCSharpTypeName(sf),
                    VariantType = GetVariantType(sf),
                    Range = GetRangeHint(sf),
                }).ToList(),
            };
        }

        return null;
    }

    private static void GenerateCode(SourceProductionContext context, ImmutableArray<ExportedStructFieldInfo> fields)
    {
        if (fields.Length == 0) return;

        var classes = fields.GroupBy(f => f.ClassName + "|" + (f.ContainingNamespace ?? ""));

        foreach (var classGroup in classes)
        {
            var first = classGroup.First();
            string className = first.ClassName;
            string ns = first.ContainingNamespace;

            var propertyEntries = new List<(string PropName, GeneratedStructField Field, string SourceFieldName)>();
            foreach (var fi in classGroup)
            {
                foreach (var sf in fi.StructFields)
                {
                    propertyEntries.Add((fi.Prefix + sf.Name.ToLower(), sf, fi.FieldName));
                }
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Godot;");
            sb.AppendLine();

            if (ns != null)
            {
                sb.AppendLine($"namespace {ns};");
                sb.AppendLine();
            }

            sb.AppendLine("[Tool]");
            sb.AppendLine($"public partial class {className}");
            sb.AppendLine("{");

            // _GetPropertyList()
            sb.AppendLine("    public override Godot.Collections.Array<Godot.Collections.Dictionary> _GetPropertyList()");
            sb.AppendLine("    {");
            sb.AppendLine("        return");
            sb.AppendLine("        [");

            foreach (var fi in classGroup)
            {
                AppendGroupEntry(sb, fi.GroupName, fi.Prefix);
                foreach (var sf in fi.StructFields)
                {
                    AppendPropertyEntry(sb, fi.Prefix, sf);
                }
            }

            sb.AppendLine("        ];");
            sb.AppendLine("    }");
            sb.AppendLine();

            // _Get()
            sb.AppendLine("    public override Variant _Get(StringName property)");
            sb.AppendLine("    {");
            sb.AppendLine("        return property.ToString() switch");
            sb.AppendLine("        {");
            foreach (var entry in propertyEntries)
            {
                sb.AppendLine($"            \"{entry.PropName}\" => {entry.SourceFieldName}.{entry.Field.Name},");
            }
            sb.AppendLine("            _ => default,");
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine();

            // _Set()
            sb.AppendLine("    public override bool _Set(StringName property, Variant value)");
            sb.AppendLine("    {");
            sb.AppendLine("        switch (property.ToString())");
            sb.AppendLine("        {");
            foreach (var entry in propertyEntries)
            {
                sb.AppendLine($"            case \"{entry.PropName}\": {entry.SourceFieldName}.{entry.Field.Name} = value.As<{entry.Field.TypeName}>(); return true;");
            }
            sb.AppendLine("        }");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");

            sb.AppendLine("}");

            context.AddSource($"{className}.ExportStruct.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private static void AppendGroupEntry(StringBuilder sb, string groupName, string prefix)
    {
        sb.AppendLine("            new() {");
        sb.AppendLine($"                {{ \"name\", \"{groupName}\" }},");
        sb.AppendLine("                { \"type\", (int)Variant.Type.Nil },");
        sb.AppendLine("                { \"usage\", (int)PropertyUsageFlags.Group },");
        sb.AppendLine($"                {{ \"hint_string\", \"{prefix}\" }},");
        sb.AppendLine("            },");
    }

    private static void AppendPropertyEntry(StringBuilder sb, string prefix, GeneratedStructField sf)
    {
        string propName = prefix + sf.Name.ToLower();
        sb.AppendLine("            new() {");
        sb.AppendLine($"                {{ \"name\", \"{propName}\" }},");
        sb.AppendLine($"                {{ \"type\", (int){sf.VariantType} }},");

        if (sf.Range != null)
        {
            string hintString = string.Format(CultureInfo.InvariantCulture,
                "{0},{1},{2}", sf.Range.Value.Min, sf.Range.Value.Max, sf.Range.Value.Step);
            sb.AppendLine("                { \"hint\", (int)PropertyHint.Range },");
            sb.AppendLine($"                {{ \"hint_string\", \"{hintString}\" }},");
        }

        sb.AppendLine("                { \"usage\", (int)PropertyUsageFlags.Default },");
        sb.AppendLine("            },");
    }

    private static string TrimUnderscore(string name)
    {
        return name.StartsWith("_") ? name.Substring(1) : name;
    }

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToUpper(name[0]) + name.Substring(1);
    }

    private static string ToSnakeCase(string name)
    {
        string trimmed = TrimUnderscore(name);
        if (string.IsNullOrEmpty(trimmed)) return "";
        return trimmed.ToLower() + "_";
    }

    private static string GetCSharpTypeName(IFieldSymbol field)
    {
        if (field.Type.SpecialType == SpecialType.System_Single) return "float";
        if (field.Type.SpecialType == SpecialType.System_Int32) return "int";
        if (field.Type.SpecialType == SpecialType.System_String) return "string";
        if (field.Type.SpecialType == SpecialType.System_Boolean) return "bool";
        return field.Type.ToDisplayString();
    }

    private static string GetVariantType(IFieldSymbol field)
    {
        if (field.Type.SpecialType == SpecialType.System_Single) return "Variant.Type.Float";
        if (field.Type.SpecialType == SpecialType.System_Int32) return "Variant.Type.Int";
        if (field.Type.SpecialType == SpecialType.System_String) return "Variant.Type.String";
        if (field.Type.SpecialType == SpecialType.System_Boolean) return "Variant.Type.Bool";

        string fullName = field.Type.ToDisplayString();
        if (fullName == "Godot.Vector2") return "Variant.Type.Vector2";
        if (fullName == "Godot.Vector3") return "Variant.Type.Vector3";
        if (fullName == "Godot.Color") return "Variant.Type.Color";

        return "Variant.Type.Nil";
    }

    private static RangeInfo? GetRangeHint(IFieldSymbol field)
    {
        var rangeAttr = field.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == InspectorRangeAttributeName);
        if (rangeAttr == null || rangeAttr.ConstructorArguments.Length < 2) return null;

        double min = Convert.ToDouble(rangeAttr.ConstructorArguments[0].Value, CultureInfo.InvariantCulture);
        double max = Convert.ToDouble(rangeAttr.ConstructorArguments[1].Value, CultureInfo.InvariantCulture);
        double step = rangeAttr.ConstructorArguments.Length >= 3
            ? Convert.ToDouble(rangeAttr.ConstructorArguments[2].Value, CultureInfo.InvariantCulture)
            : 1;

        return new RangeInfo { Min = min, Max = max, Step = step };
    }

    private struct ExportedStructFieldInfo
    {
        public string ClassName;
        public string ContainingNamespace;
        public string FieldName;
        public string GroupName;
        public string Prefix;
        public List<GeneratedStructField> StructFields;
    }

    private struct GeneratedStructField
    {
        public string Name;
        public string TypeName;
        public string VariantType;
        public RangeInfo? Range;
    }

    private struct RangeInfo
    {
        public double Min;
        public double Max;
        public double Step;
    }
}
