using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace ZeusInspector.Generators;

// Marcamos la clase como Source Generator
[Generator(LanguageNames.CSharp)]
public class MiNodoGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Buscamos todas las declaraciones de clases en el juego de Godot
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (syntaxNode, _) => syntaxNode is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax,
                transform: (ctx, _) => (INamedTypeSymbol)ctx.SemanticModel.GetDeclaredSymbol(ctx.Node)!
            );

        // 2. Generamos código basado en lo que encontramos
        context.RegisterSourceOutput(classDeclarations, (spc, source) =>
        {
            // Filtro de ejemplo: Solo actuar en clases que se llamen "MiNodoEspecial"
            if (source.Name == "MiNodoEspecial")
            {
                string namespaceName = source.ContainingNamespace.IsGlobalNamespace
                    ? ""
                    : $"namespace {source.ContainingNamespace.ToDisplayString()};\n\n";

                string generatedCode = $$"""
                // <auto-generated/>
                using Godot;
                using System;

                {{namespaceName}}public partial class {{source.Name}}
                {
                    public void SaludarDesdeGenerator()
                    {
                        GD.Print("¡Hola! Este método fue inyectado automáticamente por el Source Generator del Addon.");
                    }
                }
                """;

                // Añadimos el archivo virtual al compilador
                spc.AddSource($"{source.Name}.g.cs", SourceText.From(generatedCode, Encoding.UTF8));
            }
        });
    }
}
