<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>11</LangVersion>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
	</PropertyGroup>

	<ItemGroup>
    	<AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
    	<AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
    </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.11.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<Target Name="CopyOutputToAddon" AfterTargets="Build">
	    <ItemGroup>
	    	<AnalyzerFiles Include="$(TargetDir)*.dll" />
	    </ItemGroup>
	    <Copy SourceFiles="@(AnalyzerFiles)"
	        DestinationFolder="..\addons\ZeusInspector\analyzers\"
	        SkipUnchangedFiles="true" />
	</Target>

</Project>
