<Project>
  <ItemGroup>
    <Analyzer Include="$(MSBuildThisFileDirectory)analyzers\ZeusInspector.Generators.dll" />
    <CompilerVisibleProperty Include="GodotDisabledSourceGenerators" />
    <CompilerVisibleProperty Include="GodotProjectDir" />
    <CompilerVisibleProperty Include="GodotProjectDirBase64" />
    <CompilerVisibleProperty Include="GodotSourceGenerators" />
    <CompilerVisibleProperty Include="IsGodotToolsProject" />
  </ItemGroup>
</Project>
